export declare function init(): void;
export declare function prime(): void;
export declare function setAmbientTrack(track: string): Promise<void>;
export declare function setPhase(phase: string): void;
export declare function setProtocol(active: boolean): void;
export declare function duckNotification(): void;
export declare function setVolume(v: number): void;
export declare function getVolume(): number;
export declare function setAtmosphereVolume(v: number): void;
export declare function getAtmosphereVolume(): number;
export declare function playUISound(type: string): void;
